server:
  port: 8080

spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    tomcat:
#      max-wait: 1000
#      max-idle: 10
#      min-idle: 5
#      initial-size: 5
#    type: com.alibaba.druid.pool.DruidDataSource
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: true
#    hibernate:
#      # 自动建表
#      ddl-auto: update
#  # redis 地址配置
#  redis:
#    host: 127.0.0.1
#    port: 6379

# logging config
logging:
  config: classpath:config/log/logback-prod.xml

security:
  oauth2:
    resource:
      # user-info-uri: http://127.0.0.1:8004/auth/admin
      user-info-uri: http://127.0.0.1:8081/oauth/account